export const verifyUrl = "http://localhost:3000/user/verify"
export const blogsUrl = "http://localhost:3000/blog/protected"
export const loginUrl = "http://localhost:3000/user/login"
export const registerUrl = "http://localhost:3000/user/register"
export const publishUrl = "http://localhost:3000/blog/protected/publish"
export const unpublishUrl = "http://localhost:3000/blog/protected/unpublish"
export const addBlogUrl = "http://localhost:3000/blog/protected/add"